export const SUBMIT_QUIZ_MODAL = 'SUBMIT_QUIZ_MODAL'
export const DELETE_QUIZ_MODAL = 'DELETE_QUIZ_MODAL'
export const REPORT_QUIZ_MODAL = 'REPORT_QUIZ_MODAL'
export const REPORT_QUESTION_MODAL = 'REPORT_QUESTION_MODAL'
